### ISSUE TITLE
Here is problem

### ISSUE THREAD

**Issue by ghzmwhdk777** [fredzzhang/upt#44]
Traceback (most recent call last):
  File "inference.py", line 225, in <module>
    main(args)
  File "C:\Users\User\anaconda3\envs\colab\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "inference.py", line 150, in main
    upt = build_detector(args, conversion)
  File "C:\Users\User\PycharmProjects\hoi\UPT\upt.py", line 268, in build_detector
    detr, _, postprocessors = build_model(args)
  File "C:\Users\User\PycharmProjects\hoi\UPT\detr\models\__init__.py", line 6, in build_model
    return build(args)
  File "C:\Users\User\PycharmProjects\hoi\UPT\detr\models\detr.py", line 313, in build
    num_classes = 20 if args.dataset_file != 'coco' else 91
AttributeError: 'Namespace' object has no attribute 'dataset_file'

**Comment by ghzmwhdk777** [comment]
A lot of modifications were needed for the reference of this code to work. And I solved most of the problems. But the problem still remains.

Traceback (most recent call last):
  File "inference.py", line 225, in <module>
    main(args)
  File "C:\Users\User\anaconda3\envs\colab\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "inference.py", line 150, in main
    upt = build_detector(args, conversion)
  File "C:\Users\User\PycharmProjects\hoi\UPT\upt.py", line 276, in build_detector
    detr.backbone[0].num_channels,
  File "C:\Users\User\anaconda3\envs\colab\lib\site-packages\torch\nn\modules\module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DETRsegm' object has no attribute 'backbone'

What the hell should I do with this? Is this also a problem for args?

**Comment by ghzmwhdk777** [comment]
i really want run this project.

if you possible, give me "google colab version" please

**Comment by fredzzhang** [comment]
Hi @ghzmwhdk777,

Thanks for taking an interest in our work.

Assuming all libraries have been installed with the correct version, the code should work just fine. The last error message you posted traces back to pytorch modules, which suggest you might have installed a different version. Can you check you have installed PyTorch `1.9.0`?

Fred.

**Comment by ghzmwhdk777** [comment]
Yes, it's not a version issue.
I'll try my best first and then ask you again. Thank you for your answer.
