### ISSUE TITLE
There is still a problem.

### ISSUE THREAD

**Issue by ghzmwhdk777** [fredzzhang/upt#45]
Traceback (most recent call last):
  File "inference.py", line 225, in <module>
    main(args)
  File "C:\Users\User\anaconda3\envs\colab\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "inference.py", line 150, in main
    upt = build_detector(args, conversion)
  File "C:\Users\User\PycharmProjects\hoi\UPT\upt.py", line 276, in build_detector
    detr.backbone[0].num_channels,
  File "C:\Users\User\anaconda3\envs\colab\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DETRsegm' object has no attribute 'backbone'

----------------------------------------------------------

I changed the torch version and tried it in the collab environment, but the problem still occurs in the same place. 

If possible, can you tell me all libraries using "**pip freeze > requirements.txt**"?

If it is not possible to disclose it externally, I would appreciate it if you could send it to _ghzmwhdk777@naver.com_.

**Comment by fredzzhang** [comment]
Hi @ghzmwhdk777,

Here is the list you wanted. Hopefully it will help you resolve the problem.

```
argcomplete @ file:///home/conda/feedstock_root/build_artifacts/argcomplete_1619128689661/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1610522577486/work
async-generator==1.10
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
brotlipy==0.7.0
certifi==2021.5.30
cffi @ file:///tmp/build/80754af9/cffi_1606255099073/work
chardet @ file:///tmp/build/80754af9/chardet_1605303159953/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
conda==4.9.2
conda-build==3.20.5
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018138503/work
cryptography @ file:///tmp/build/80754af9/cryptography_1605544449973/work
cycler==0.10.0
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1605612043231/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
filelock==3.0.12
glob2==0.7
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1630267469306/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1631291095936/work/dist/ipykernel-6.4.1-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1632763775723/work
ipython-genutils==0.2.0
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1610146791823/work
Jinja2==2.11.2
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1633119270293/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1632941645931/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1631852710654/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
kiwisolver==1.3.1
libarchive-c==2.9
MarkupSafe @ file:///tmp/build/80754af9/markupsafe_1594371495811/work
matplotlib==3.3.3
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1624941291602/work
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1629120697898/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1632535944093/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1631733685426/work
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1603479632437/work
olefile==0.46
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///tmp/build/80754af9/pillow_1603822253009/work
pkginfo==1.6.1
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1622586138406/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1629903925368/work
psutil @ file:///tmp/build/80754af9/psutil_1598370249042/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1606517880428/work
pyparsing==2.4.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1610146801408/work
PySocks @ file:///tmp/build/80754af9/pysocks_1594394576006/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz @ file:///tmp/build/80754af9/pytz_1606604771399/work
PyYAML==5.3.1
pyzmq==20.0.0
requests @ file:///tmp/build/80754af9/requests_1606691187061/work
ruamel-yaml==0.15.87
scipy==1.5.4
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
six @ file:///tmp/build/80754af9/six_1605205313296/work
soupsieve==2.0.1
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1631128156863/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
torch==1.9.0
torchaudio==0.9.0a0+33b2469
torchvision==0.10.0
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094704591/work
tqdm @ file:///tmp/build/80754af9/tqdm_1606938474023/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1630423529112/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1611751222202/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1633302054558/work
```

**Comment by ghzmwhdk777** [comment]
oh thx. can i get "conda export" option --> (to get environments.yml)??

**Comment by fredzzhang** [comment]
The libraries installed under `conda` should already be listed with `pip freeze` apart from some native packages. But anyways here is the list after running `conda list`

```
# packages in environment at /home/fred/miniconda3/envs/pocket:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argcomplete               1.12.3             pyhd8ed1ab_2    conda-forge
argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0  
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py37h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py37h89c1867_0    conda-forge
cffi                      1.14.4           py37h261ae71_0  
chardet                   3.0.4           py37h06a4308_1003  
cloudpickle               1.6.0                      py_0    anaconda
conda                     4.9.2            py37h06a4308_0  
conda-build               3.20.5                   py37_1  
conda-package-handling    1.7.2            py37h03888b9_0  
cryptography              3.2.1            py37h3c74f83_1  
cudatoolkit               11.1.74              h6bb024c_0    nvidia
cycler                    0.10.0                   pypi_0    pypi
debugpy                   1.2.0            py37h745909e_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.0.12                     py_0  
freetype                  2.10.4               h5ab3b9f_0  
glob2                     0.7                        py_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
importlib-metadata        4.8.1            py37h89c1867_0    conda-forge
importlib_metadata        4.8.1                hd8ed1ab_0    conda-forge
intel-openmp              2020.2                      254  
ipykernel                 6.4.1            py37h6531663_0    conda-forge
ipython                   7.28.0           py37h6531663_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py37h89c1867_2    conda-forge
jinja2                    2.11.2                     py_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                4.0.1              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.5              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py37h89c1867_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.4.2                h62408e4_0  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1d223b6_9    conda-forge
libgomp                   11.2.0               h1d223b6_9    conda-forge
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
liblief                   0.10.1               he6710b0_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.1.0                h2733197_1  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
lz4-c                     1.9.2                heb0550a_3  
markupsafe                1.1.1            py37h14c3975_1  
matplotlib                3.3.3                    pypi_0    pypi
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py37h5e8e339_1004    conda-forge
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.2.0            py37h89c1867_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                hbbd107a_1  
ninja                     1.10.2           py37hff7bd54_0  
notebook                  6.4.4              pyha770c72_0    conda-forge
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46                       py_0  
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandoc                    2.14.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
patchelf                  0.12                 he6710b0_0  
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py37he98fc37_0  
pip                       20.3             py37h06a4308_0  
pkginfo                   1.6.1            py37h06a4308_0  
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
psutil                    5.7.2            py37h7b6447c_0  
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-lief                   0.10.1           py37h403a769_0  
pycosat                   0.6.3            py37h27cfd23_0  
pycparser                 2.20                       py_2  
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.0             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
pysocks                   1.7.1                    py37_1  
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
python-libarchive-c       2.9                        py_0  
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.9.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
pytz                      2020.4             pyhd3eb1b0_0  
pyyaml                    5.3.1            py37h7b6447c_1  
pyzmq                     20.0.0           py37h5a562af_1    conda-forge
readline                  8.0                  h7b6447c_0  
requests                  2.25.0             pyhd3eb1b0_0  
ripgrep                   12.1.1                        0  
ruamel_yaml               0.15.87          py37h7b6447c_1  
scipy                     1.5.4                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                50.3.2           py37h06a4308_2  
six                       1.15.0           py37h06a4308_0  
soupsieve                 2.0.1                      py_0  
sqlite                    3.33.0               h62c20be_0  
terminado                 0.12.1           py37h89c1867_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               hbc83047_0  
torchaudio                0.9.0                      py37    pytorch
torchvision               0.10.0               py37_cu111    pytorch
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.54.0             pyhd3eb1b0_0  
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
typing_extensions         3.7.4.3            pyh06a4308_0  
urllib3                   1.25.11                    py_0  
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.0             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zeromq                    4.3.3                h58526e2_3    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
```

**Comment by ghzmwhdk777** [comment]
thx. i will try today
